### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by codenameakshay** [Hash-Studios/algoking#5]
Add license in readme.md file.

**Comment by DeadEnglish** [comment]
Hey, i'd love to take this if possible. Let me know what licence you'd like adding!

**Comment by swai-collins** [comment]
Please assign this to me

**Comment by codenameakshay** [comment]
@DeadEnglish Add the license BSD-3 in readme.md from the file License.txt

**Comment by DeadEnglish** [comment]
Should be on the following PR #7 😄
